"""Roof Questions: 60 homeowner questions answered by RingaRoofer (our own editorial answers, clearly labeled; no made-up users).
Buyer wording rules apply (build blocks banned words). Money/insurance questions are deliberately left out: the buyer bans that wording."""
# (slug, question, category, photo, service_url, short answer, [steps/points])
CATS = [("leaks", "Roof leaks"), ("repair", "Roof repair"), ("replace", "New roofs and replacement"), ("storm", "Storm, wind and hail"),
        ("materials", "Roofing materials"), ("care", "Inspection and upkeep"), ("hiring", "Hiring a roofer and the job")]
Q = [
 # ---------------- leaks
 ("why-is-my-roof-leaking", "Why is my roof leaking?", "leaks", "ceiling", "/services/roof-leak-repair/",
  "Most roof leaks start at flashing around vents, walls and valleys, at cracked pipe boots, or where shingles are missing or lifted. Older roofs can leak in several places as the shingles wear out.",
  ["Flashing that has pulled away or rusted.", "Rubber pipe boots that have cracked in the sun.", "Missing, cracked or lifted shingles after wind.", "Ice dams in cold climates pushing water under shingles.", "Worn shingles near the end of their life."]),
 ("roof-leaking-in-heavy-rain-only", "Why does my roof only leak in heavy rain?", "leaks", "storm2", "/services/roof-leak-repair/",
  "Heavy, wind-driven rain reaches places normal rain never touches: the edges of lifted shingles, flashing seams and vent openings. A leak that only shows in big storms is still a real opening and usually grows.",
  ["Note which way the wind was blowing when it leaked.", "Check the attic during or right after the storm with a flashlight.", "Have a roofer check flashing and shingle edges on that side of the roof."]),
 ("what-to-do-when-roof-is-leaking", "What should I do right now if my roof is leaking?", "leaks", "ceiling", "/services/roof-leak-repair/",
  "Catch the water, move belongings, keep out of rooms with a bulging ceiling, take photos and call a roofer. Don't climb onto a wet roof.",
  ["Put a bucket under the drip and a towel under the bucket.", "If the ceiling bulges, keep people out of the room.", "Switch off power to wet areas only from a dry spot.", "Photograph the ceiling and the roof from the ground.", "Call a roofer; a tarp can stop more water until the repair."]),
 ("ceiling-stain-but-roof-looks-fine", "Why is there a water stain on my ceiling when the roof looks fine?", "leaks", "ceiling", "/services/roof-leak-repair/",
  "Water travels along rafters and decking before it drips, so the stain is often several feet from where water gets in. Small openings around vents and flashing aren't visible from the ground.",
  ["Check the attic above the stain for wet wood or insulation.", "Look for a pipe, vent or roof valley uphill of the stain.", "Rule out a plumbing or bathroom leak if the stain is under a bathroom.", "Have a roofer trace it to the entry point."]),
 ("can-a-roof-leak-be-fixed-in-winter", "Can a roof leak be fixed in winter?", "leaks", "shingles2", "/services/roof-leak-repair/",
  "Yes. Roofers repair leaks year-round. In very cold weather some sealants and shingles don't seal well, so a roofer may make a temporary fix and finish the job on a milder day.",
  ["Call as soon as you see it; winter leaks spread under snow and ice.", "Keep the attic area under the leak dry if you can reach it safely.", "Ask the roofer whether the fix is temporary or permanent."]),
 ("is-a-roof-leak-an-emergency", "Is a roof leak an emergency?", "leaks", "oldroof", "/services/emergency-roof-repair/",
  "An active leak into living space, a sagging ceiling, or part of the roof open to the sky should be handled the same day. A slow stain that isn't growing can usually wait a few days, but not weeks.",
  ["Same day: water coming in, sagging ceiling, opening in the roof.", "Within days: a new stain, a small drip in the attic.", "Don't wait: small leaks rot decking and soak insulation."]),
 ("roof-leak-around-vent-pipe", "How do I fix a roof leak around a vent pipe?", "leaks", "shingles", "/services/roof-repair/",
  "Most vent-pipe leaks come from the rubber boot around the pipe cracking in the sun. A roofer replaces the boot, or adds a new one over it, and reseals the shingles around it.",
  ["Look for a cracked or split rubber collar around the pipe.", "Check the attic for water running down the pipe.", "Pipe boots are a routine repair for a roofer."]),
 ("ice-dams-causing-leaks", "Why do ice dams cause roof leaks?", "leaks", "shingles2", "/services/roof-leak-repair/",
  "Heat escaping from the house melts snow on the roof. The water refreezes at the cold edge and builds a ridge of ice, so meltwater backs up under the shingles and leaks inside.",
  ["Don't chip ice off the roof; it breaks shingles.", "A roof rake can clear snow from the bottom few feet.", "Long term: attic insulation and ventilation reduce ice dams.", "Ice and water barrier under the shingles helps on new roofs."]),
 # ---------------- repair
 ("repair-or-replace-roof", "Should I repair or replace my roof?", "repair", "tearoff", "/services/roof-replacement/",
  "Repair when the problem is in one area and the rest of the roof is sound. Replace when shingles are worn across the roof, leaks keep coming back in different places, or the roof is near the end of its life.",
  ["How old is the roof? Shingles past about 20 years often point to replacement.", "Is the problem in one spot or across many slopes?", "Is the decking soft in several places?", "Ask the roofer to show you photos of what they found."]),
 ("can-you-replace-a-few-shingles", "Can you replace just a few shingles?", "repair", "shingles", "/services/roof-repair/",
  "Yes. Replacing a handful of missing or cracked shingles is a routine repair. On older roofs the exact color can be hard to match, so the patch may look slightly different.",
  ["Keep any leftover shingles from the original job; they match.", "Ask the roofer to check the surrounding shingles too.", "Several patches in one season can be a sign the roof is wearing out."]),
 ("how-long-does-a-roof-repair-take", "How long does a roof repair take?", "repair", "roofer", "/services/roof-repair/",
  "Most repairs take a few hours to a day once the roofer is on site. Bigger repairs, like replacing a section of decking, can take longer, and weather can push the start date.",
  ["Small repairs: a few hours.", "Flashing or decking sections: up to a day or two.", "After storms, roofers are busy, so book early."]),
 ("what-is-roof-flashing", "What is roof flashing and why does it fail?", "repair", "shingles", "/services/roof-repair/",
  "Flashing is thin metal that seals the joints where the roof meets walls, vents and valleys. It fails when it rusts, loosens, or the sealant around it dries out, letting water slip in.",
  ["Common spots: where the roof meets a wall, around vents, in valleys.", "Signs: rust, gaps, lifted edges, stains below those spots.", "Fixing flashing is usually a repair, not a re-roof."]),
 ("sagging-roof-what-it-means", "What does a sagging roof mean?", "repair", "oldroof", "/services/roof-repair/",
  "A sag usually means wet or rotted decking, or a problem with the framing below it. It needs attention soon, because it often gets worse and can let water in.",
  ["Look in the attic for wet or dark wood under the sag.", "Keep heavy snow off the area if you can do it safely from the ground.", "Have a roofer inspect it before the next big storm."]),
 ("nail-pops-on-roof", "What are nail pops on a roof?", "repair", "shingles2", "/services/roof-repair/",
  "Nail pops are nails that push up through shingles as the wood below expands and shrinks. They lift the shingle above them and can let water in over time.",
  ["They look like small bumps under the shingles.", "A roofer resets or replaces the nail and the shingle over it.", "Lots of them can point to ventilation or decking issues."]),
 ("roof-repair-in-the-rain", "Can roofers repair a roof in the rain?", "repair", "storm2", "/services/roof-tarping/",
  "Roofers avoid working on wet roofs because it isn't safe and materials don't seal well. They can tarp a leaking roof in bad weather and come back to repair it when it's dry.",
  ["Ask for a tarp if rain is in the forecast.", "Keep buckets in place until the permanent repair.", "Photos of the leak help the roofer plan the repair."]),
 ("missing-shingles-after-wind", "What should I do about missing shingles after wind?", "repair", "oldroof", "/services/storm-roof-repair/",
  "Get them replaced soon. The felt underneath isn't meant to face weather for long, and the next rain can leak through. Photograph the roof from the ground and call a roofer.",
  ["Pick up shingle pieces from the yard and keep them.", "Check ceilings and the attic for new stains.", "Stay off the roof; wind-loosened shingles are slippery."]),
 # ---------------- replace
 ("signs-you-need-a-new-roof", "How do I know if I need a new roof?", "replace", "tearoff", "/services/roof-replacement/",
  "Curling or cracked shingles across the roof, bald spots, granules piling up at downspouts, leaks in more than one place, a sagging roofline or a roof past about 20 to 25 years all point to replacement.",
  ["Curling, cupping or cracking on several slopes.", "Bare patches where granules are gone.", "Daylight through the attic boards.", "Repeat leaks in different places."]),
 ("how-long-does-roof-replacement-take", "How long does a roof replacement take?", "replace", "newroof2", "/services/roof-replacement/",
  "Most homes take one to three days. Large or steep roofs, tile and slate, or extra decking repairs can take longer, and weather can add days.",
  ["Day 1: tear-off and decking check.", "Day 1 to 3: underlayment, flashing and new roofing.", "Final day: cleanup and walkthrough."]),
 ("what-happens-during-roof-replacement", "What happens during a roof replacement?", "replace", "tearoff", "/services/roof-replacement/",
  "The old roofing is torn off, the decking is checked and repaired, new underlayment and flashing go on, then the new roofing, ridge and vents. The crew cleans up and checks for nails.",
  ["Inspection and material choice.", "Tear-off down to the decking.", "Decking repairs where needed.", "Underlayment, ice and water barrier, flashing.", "New roofing, ridge caps and vents, then cleanup."]),
 ("can-new-roof-go-over-old-roof", "Can a new roof go over the old one?", "replace", "shingles2", "/services/new-roof/",
  "Some areas allow a second layer of shingles, but many roofers prefer a full tear-off so they can check and repair the decking underneath. Ask the roofer what local rules allow and what they recommend.",
  ["A second layer adds weight.", "Problems in the decking stay hidden under a layover.", "Most areas allow two layers at most."]),
 ("good-time-to-replace-a-roof", "When is a good time of year to replace a roof?", "replace", "newroof", "/services/roof-replacement/",
  "Late spring through fall is ideal in most of the country because shingles seal well in mild weather. Roofers work year-round, though, and a failing roof shouldn't wait for the season.",
  ["Spring and fall are the busiest seasons, so book ahead.", "Winter installs are possible on mild days.", "In hurricane areas, plan before storm season."]),
 ("do-i-need-to-be-home-for-new-roof", "Do I need to be home during a roof replacement?", "replace", "newroof2", "/services/roof-replacement/",
  "Not always, but expect noise, a busy driveway and the roofer needing attic access. Agree the details before the start date.",
  ["Move cars out of the driveway.", "Take down wall hangings on top-floor walls; hammering shakes them.", "Keep pets and kids away from the work area."]),
 ("how-long-does-a-roof-last", "How long does a roof last?", "replace", "aerial", "/library/how-long-does-a-roof-last/",
  "Asphalt shingles commonly last 20 to 30 years, metal 40 or more, tile and slate much longer with care, and flat roofs 15 to 30 years. Climate, ventilation and installation quality make a big difference.",
  ["Hail, high wind and intense sun shorten roof life.", "Good attic ventilation helps it last.", "Fixing small problems early keeps it going longer."]),
 ("what-is-a-re-roof", "What is a re-roof?", "replace", "roofer2", "/services/new-roof/",
  "A re-roof replaces the roofing on an existing home, usually with a full tear-off of the old layers. It's different from a new roof on new construction or an addition.",
  ["Re-roof: existing home, old roofing comes off.", "New roof: new construction or a change of material.", "Both start with checking the decking."]),
 ("how-to-prepare-for-roof-replacement", "How do I prepare my home for a roof replacement?", "replace", "roofer", "/services/roof-replacement/",
  "Clear the driveway, move outdoor furniture and grills, cover items in the attic, and take fragile things off top-floor walls and shelves. Mark sprinkler heads and anything fragile near the house.",
  ["Clear access for a dumpster and delivery.", "Cover attic storage with sheets for falling dust.", "Trim branches that hang over the roof.", "Let neighbors know about the noise."]),
 ("switch-from-shingles-to-metal", "Can I switch from shingles to a metal roof?", "replace", "metal", "/roof-types/metal/",
  "Yes. Many homeowners re-roof in metal. A roofer checks the structure and decking and explains whether the old shingles come off first.",
  ["Metal is lighter than many roofs, so most homes handle it.", "Standing seam hides the fasteners.", "Ask about snow guards in snowy areas."]),
 # ---------------- storm
 ("how-to-tell-if-hail-hit-roof", "How can I tell if hail hit my roof?", "storm", "hail", "/services/hail-roof-repair/",
  "Look for dents on metal vents, flashing and outdoor equipment, granules washing out of downspouts, and shingle pieces in the yard. Most hail marks on shingles are only visible up close, so a roofer's inspection matters.",
  ["Write down the date and hail size if you saw it.", "Check soft metals like vents and mailboxes for dents.", "Look for dark spots where granules were knocked off.", "Stay off the roof; call for an inspection."]),
 ("what-size-hail-hurts-a-roof", "What size hail can hurt a roof?", "storm", "hail2", "/services/hail-roof-repair/",
  "Hail about one inch across and larger can bruise asphalt shingles. Bigger stones can crack tile and dent metal. Older, brittle shingles can be hurt by smaller hail.",
  ["Pea to dime size: usually cosmetic.", "Quarter size and up: worth an inspection.", "Golf ball size and up: inspection soon."]),
 ("roof-check-after-storm", "Should I get my roof checked after a storm?", "storm", "storm", "/services/roof-inspection/",
  "Yes, after hail, high wind or a hurricane. Lifted or bruised shingles may not leak right away but can fail months later.",
  ["Look from the ground for missing or out-of-place shingles.", "Check ceilings and the attic for new stains.", "Call for an inspection within a few days."]),
 ("what-wind-speed-blows-off-shingles", "What wind speed can blow shingles off a roof?", "storm", "storm2", "/services/storm-roof-repair/",
  "Gusts around 50 to 60 mph can lift older or poorly sealed shingles. Newer wind-resistant shingles, installed well, hold up to much stronger wind.",
  ["Edges and ridges lose shingles first.", "Creased shingles can look fine but no longer seal.", "Have lifted areas resealed or replaced."]),
 ("how-to-spot-storm-chasers", "How do I avoid storm chasers after a storm?", "storm", "aerial2", "/services/storm-roof-repair/",
  "Take your time. Ask for a local address and references, get the scope of work in writing, and don't sign anything on the doorstep or hand over a large payment up front.",
  ["Be wary of crews that just showed up in town.", "Ask how long they've worked in your area.", "Confirm the credentials your state requires.", "Don't let anyone pressure you into signing that day."]),
 ("tree-fell-on-roof", "A tree fell on my roof. What do I do?", "storm", "oldroof", "/services/emergency-roof-repair/",
  "Get everyone out of the affected rooms, stay away from downed power lines, and call 911 if anyone is hurt or lines are down. Then call a roofer to secure the roof; tree removal may need a separate crew.",
  ["Safety first: leave rooms under the tree.", "Call the utility about any downed lines.", "Photograph everything before anything is moved.", "A roofer can tarp the opening once the tree is off."]),
 ("roof-tarp-how-long", "How long can a tarp stay on a roof?", "storm", "edge", "/services/roof-tarping/",
  "A properly secured tarp is a short-term fix, usually for a few weeks until the permanent repair. Sun and wind wear tarps out, and they can trap moisture if left too long.",
  ["Check the tarp after every storm.", "Book the permanent repair as soon as you can.", "Let a roofer install it; DIY tarps often blow off."]),
 ("hurricane-roof-prep", "How do I get my roof ready for hurricane season?", "storm", "storm", "/services/roof-inspection/",
  "Have the roof inspected before the season, fix loose shingles and flashing, trim branches over the roof, and know who to call for a tarp afterward.",
  ["Inspection in late spring.", "Secure loose shingles, ridge caps and flashing.", "Trim trees near the house.", "Keep a roofer's number handy before storms hit."]),
 # ---------------- materials
 ("asphalt-shingles-vs-metal", "Asphalt shingles or a metal roof: which is right for me?", "materials", "metal", "/library/choosing-a-roofing-material/",
  "Shingles suit almost any home and are the most common choice. Metal lasts much longer, sheds snow and handles wind well. The choice comes down to how long you'll stay, climate and the look you want.",
  ["Shingles: 20 to 30 years, many colors and styles.", "Metal: 40+ years, light, good in snow and heat.", "Ask a roofer to compare both for your house."]),
 ("architectural-vs-three-tab-shingles", "What's the difference between architectural and three-tab shingles?", "materials", "shingles2", "/roof-types/asphalt-shingle/",
  "Architectural shingles are thicker, layered and more textured, and they handle wind better. Three-tab shingles are flat and single-layer, and many roofers now install architectural shingles by default.",
  ["Architectural: dimensional look, longer life.", "Three-tab: flatter look, older style.", "Both come in many colors."]),
 ("is-a-metal-roof-noisy", "Is a metal roof noisy in the rain?", "materials", "metal", "/roof-types/metal/",
  "Not usually. Over solid decking and underlayment, a metal roof sounds much like any other roof. The loud rain on metal you may picture is from barns with no decking.",
  ["Solid decking and underlayment dampen the sound.", "Attic insulation helps further.", "Ask the roofer how they'll install it."]),
 ("standing-seam-metal-roof", "What is a standing seam metal roof?", "materials", "metal", "/roof-types/metal/",
  "Standing seam panels run from ridge to eave with raised seams that lock together and hide the fasteners. With no exposed screws, there are fewer places for water to get in.",
  ["Clean, modern look.", "Hidden fasteners mean fewer leak points.", "Long life with little upkeep."]),
 ("flat-roof-options", "What are the options for a flat roof?", "materials", "flat", "/roof-types/flat/",
  "The main choices are TPO (a white single-ply membrane), EPDM (black rubber) and modified bitumen. Each needs good drainage, since water moves slowly on flat roofs.",
  ["TPO: white, reflects heat, heat-welded seams.", "EPDM: rubber, flexible, long track record.", "Modified bitumen: layered, tough, common on porches and additions."]),
 ("water-pooling-on-flat-roof", "Why does water pool on my flat roof?", "materials", "flat2", "/roof-types/flat/",
  "Clogged drains, sagging decking or a poor slope. Water that sits for more than a couple of days after rain wears out the membrane faster and finds any weak seam.",
  ["Clear drains and scuppers of leaves.", "Mark where water sits after rain.", "A roofer can add slope, drains or crickets."]),
 ("tile-roof-repair", "Can a tile roof be repaired?", "materials", "tile", "/roof-types/tile/",
  "Yes. Cracked or slipped tiles can be replaced one at a time. Often the real issue is the underlayment beneath the tiles, which wears out before the tiles do.",
  ["Don't walk on tile; it cracks underfoot.", "Leaks with intact tiles often mean worn underlayment.", "Keep spare tiles from the original roof."]),
 ("slate-roof-life", "How long does a slate roof last?", "materials", "shingles2", "/roof-types/slate/",
  "Natural slate can last 75 years or more. The nails and flashing often wear out before the slate itself, so many slate roofs are repaired rather than replaced.",
  ["Repairs are done slate by slate.", "Use a roofer who works with slate.", "Copper flashing is common on slate roofs."]),
 ("cedar-shake-upkeep", "How do I keep a cedar shake roof lasting?", "materials", "shake", "/roof-types/cedar-shake/",
  "Keep it clear of leaves and moss, keep branches trimmed back so it dries out, and replace split or curled shakes early.",
  ["Airflow under and around the roof matters.", "Moss holds moisture; have it cleared carefully.", "Check after storms for split shakes."]),
 ("impact-resistant-shingles", "What are impact-resistant shingles?", "materials", "hail", "/roof-types/asphalt-shingle/",
  "Shingles made to resist hail better than standard shingles, often called Class 4. They're popular in hail-prone states like Texas, Colorado and Oklahoma.",
  ["Thicker or rubber-modified shingles.", "Worth asking about in hail country.", "A roofer can show you options for your area."]),
 # ---------------- care
 ("how-often-roof-inspection", "How often should I have my roof inspected?", "care", "inspect", "/services/roof-inspection/",
  "Once a year is a good habit, plus after major storms. Roofs over 15 years old benefit from more regular checks.",
  ["Annual inspection, ideally spring or fall.", "After hail, high wind or hurricanes.", "Before buying or selling a home."]),
 ("what-does-roof-inspection-include", "What does a roof inspection include?", "care", "inspect", "/services/roof-inspection/",
  "A roofer checks shingles or roofing, flashing, vent boots, ridge caps, the attic for stains and ventilation, and the decking for soft spots. Ask for photos of anything they find.",
  ["Outside: roofing, flashing, vents, edges.", "Inside: attic stains, daylight, ventilation, wet insulation.", "You get: photos and a plain explanation."]),
 ("moss-on-roof", "Is moss on my roof a problem?", "care", "shake", "/services/roof-repair/",
  "Yes, over time. Moss holds moisture against the roof and can lift shingle edges. It's most common on shady, damp slopes.",
  ["Don't pressure wash; it strips granules.", "Have it removed gently and treated.", "Trim branches to let in sun."]),
 ("roof-granules-in-downspout", "Why are there shingle granules in my downspouts?", "care", "shingles2", "/services/roof-inspection/",
  "A few granules are normal on a new roof. A lot of them on an older roof means the shingles are wearing out, or hail knocked them loose.",
  ["New roof: some granule loss is normal.", "Older roof: heavy loss points to replacement soon.", "After hail: get an inspection."]),
 ("attic-ventilation-and-roof", "Why does attic ventilation matter for my roof?", "care", "aerial2", "/services/roof-inspection/",
  "Good ventilation keeps the attic cooler in summer and drier in winter. Poor ventilation cooks shingles from below, causes ice dams and leads to moisture and mold.",
  ["Signs of poor ventilation: very hot attic, frost on nails in winter.", "Intake vents near the eaves, exhaust vents near the ridge.", "A roofer can check during an inspection."]),
 ("daylight-in-attic", "I can see daylight in my attic. Is that bad?", "care", "oldroof", "/services/roof-repair/",
  "Daylight through the roof boards means there's an opening where water can get in too. Light at ridge or eave vents can be normal; light through the roof deck isn't.",
  ["Note where the light comes through.", "Check for water stains around it.", "Have a roofer look before the next rain."]),
 ("branches-touching-roof", "Do branches touching the roof cause problems?", "care", "aerial", "/services/roof-repair/",
  "Yes. Branches scrape off granules, drop debris that holds moisture, and can break shingles or fall in storms. Keep them several feet away from the roof.",
  ["Trim branches back about 6 feet or more.", "Large limbs: use a tree service.", "Clear debris from valleys after storms."]),
 ("roof-checklist-before-winter", "What should I check on my roof before winter?", "care", "shingles", "/services/roof-inspection/",
  "Look for missing or lifted shingles, loose flashing, worn vent boots and clogged valleys, and make sure the attic is well insulated and ventilated to limit ice dams.",
  ["Fix small leaks now; they spread under snow.", "Clear debris from valleys.", "Check attic insulation and vents.", "Book repairs before the cold sets in."]),
 # ---------------- hiring
 ("how-to-find-a-roofer-near-me", "How do I find a good roofer near me?", "hiring", "roofer2", "/roofers-near-me/",
  "Ask how long they've worked in your area, ask for local references, confirm the credentials your state requires, and get the scope of work in writing. Or call RingaRoofer and we'll connect you with a local roofing company.",
  ["Local address and references.", "Credentials your state requires.", "A written scope of work.", "Clear answers about timing and cleanup."]),
 ("questions-to-ask-a-roofer", "What questions should I ask a roofer?", "hiring", "inspect", "/roofers-near-me/",
  "Ask how long they've worked locally, who will be on the roof, what the written scope includes, how they protect your property, how they handle surprises like rotten decking, and how cleanup works.",
  ["Who does the work: their crew or another company?", "What exactly is included in writing?", "What happens if they find soft decking?", "How long will it take and when can they start?"]),
 ("how-fast-can-a-roofer-come", "How fast can a roofer come out?", "hiring", "roofer", "/services/emergency-roof-repair/",
  "Often within a few days, and the same or next day for active leaks or open roofs. After big storms roofers book up quickly, so call early.",
  ["Active leak: say so when you call.", "After storms: expect a wait; tarping comes first.", "Routine repairs: usually within the week."]),
 ("do-roofers-work-in-winter", "Do roofers work in winter?", "hiring", "shingles2", "/services/roof-repair/",
  "Yes. Roofers repair leaks and handle emergencies year-round, and many replace roofs in winter when the weather allows.",
  ["Mild winter days are fine for most work.", "Some materials seal better when it's warmer.", "Emergency tarps go on in any season."]),
 ("roofer-says-whole-roof-needs-replacing", "A roofer says my whole roof needs replacing. How do I know?", "hiring", "tearoff", "/services/roof-inspection/",
  "Ask for photos of the problems on each slope and an explanation of why a repair won't hold. It's reasonable to get a second roofer's opinion before a big decision.",
  ["Photos of every slope, not just one area.", "Age of the roof and how widespread the wear is.", "A second opinion on any big job."]),
 ("roofing-after-buying-a-house", "I just bought a house. Should I get the roof checked?", "hiring", "newroof", "/services/roof-inspection/",
  "Yes. A roof inspection gives you a baseline: how old it is, what needs attention soon and what can wait. It's much easier to plan than to react to a leak.",
  ["Ask the previous owner for the roof's age if you can.", "Fix small problems early.", "Plan ahead if the roof is near the end of its life."]),
 ("what-is-included-in-roof-job", "What should be written down before a roofing job starts?", "hiring", "roofer2", "/services/roof-replacement/",
  "The scope of work: materials and color, what gets torn off, how decking repairs are handled, flashing and vents, start and finish timing, cleanup, and who to call with questions.",
  ["Materials, brand and color.", "Tear-off and decking plan.", "Flashing, vents and ridge details.", "Timing and cleanup."]),
 ("roofer-door-to-door", "Someone knocked on my door offering a new roof. What should I do?", "hiring", "aerial2", "/roofers-near-me/",
  "Don't sign anything on the doorstep. Ask for a local address, references and the credentials your state requires, and take time to get a second opinion.",
  ["Common after storms in hail and hurricane areas.", "Check how long they've been in your area.", "Never feel pressured to decide that day."]),
]
assert len(Q) == 60, len(Q)
