"""RingaRoofer content. Every word here is checked by build.py against the buyer's banned wording.
Never add: free, estimate(s), licensed, insured, bonded, cheap/low rates, affordable, discount, price/cost wording,
gutters, windows, siding, or any non-roofing service."""

PHONE = "(855) 635-9281"
TEL = "+18556359281"
EMAIL = "contact@ringaroofer.com"
URL = "https://ringaroofer.com"

# ---------------------------------------------------------------- services
# slug, name, short, icon, h1, lead, title, desc, sections [(h2, html)], faqs, ad_group
SERVICES = [
 dict(slug="roof-repair", name="Roof Repair", icon="hammer", short="Shingles, flashing, vents, ridge caps and sagging sections.",
  title="Roof Repair Near You | Call a Local Roofer | RingaRoofer",
  desc="Need roof repair? One call connects you with a local roofing company for shingle, flashing, vent and ridge repairs. Call (855) 635-9281.",
  h1="Roof repair near you, from one call",
  lead="Missing shingles, lifted flashing, a cracked vent boot or a sagging section. Call and we'll connect you with a roofing company that serves your area.",
  sections=[
   ("Common roof repairs", "<ul class='ticks'><li><b>Missing or lifted shingles</b> after wind, age or a storm.</li><li><b>Flashing repair</b> where the roof meets walls, valleys and vents.</li><li><b>Vent boot and pipe collar repair</b>, a frequent source of slow leaks.</li><li><b>Ridge cap repair</b> when caps crack or blow off.</li><li><b>Soft or sagging spots</b> that point to wet decking underneath.</li><li><b>Nail pops and exposed fasteners</b> that let water in over time.</li></ul>"),
   ("Repair or replace?", "<p>Most roofs can be repaired when the problem is local: a handful of shingles, one flashing detail, a single vent. Replacement starts to make sense when problems repeat across the roof, the shingles are curling or bald of granules, or the decking is soft in several places.</p><p>A roofer who looks at the roof in person can tell you which one you're facing. Ask them to show you photos of what they found.</p>"),
   ("What to do before the roofer arrives", "<ol><li>Move belongings away from any drip and catch water in a bucket.</li><li>Take photos of the ceiling and anything you can see from the ground.</li><li>Stay off the roof, especially if it's wet or steep.</li><li>Write down when you first noticed the problem and what the weather was.</li></ol>"),
  ],
  faqs=[("How fast can a roofer come out?", "It depends on your area and the season. Many roofing companies in our network schedule repairs within a few days, and sooner for active leaks."),
        ("Can one or two shingles really be repaired?", "Yes. Replacing a few shingles is a routine repair. Matching the color of an older roof can be harder, so ask the roofer what they can source."),
        ("Do you do the repair yourselves?", "No. RingaRoofer is a referral service. The roofing company you speak with does the work and agrees the details with you directly.")],
  group="Roof Repair"),
 dict(slug="roof-leak-repair", name="Roof Leak Repair", icon="drop", short="Active leaks, ceiling stains and drips during rain.",
  title="Roof Leak Repair Near You | Leaking Roof? Call Now | RingaRoofer",
  desc="Roof leaking? Call (855) 635-9281 to connect with a local roofer for roof leak repair. Stains, drips and leaks during rain, handled fast.",
  h1="Roof leaking? Get a roofer on the phone today",
  lead="A ceiling stain, a drip during rain or water running down a wall. Leaks get worse the longer they run, so call now and we'll connect you with a roofer near you.",
  sections=[
   ("Where roof leaks usually start", "<ul class='ticks'><li><b>Flashing</b> around vents, walls and valleys.</li><li><b>Pipe boots</b> whose rubber seals have cracked.</li><li><b>Missing or cracked shingles</b> after wind or hail.</li><li><b>Ice dams</b> in cold climates, pushing meltwater under shingles.</li><li><b>Worn roofing</b> at the end of its life, leaking in several spots.</li></ul><p>Water travels along rafters and decking, so the stain on your ceiling is often a few feet from where the water gets in. A roofer finds the entry point, not just the stain.</p>"),
   ("Do this now", "<ol><li>Catch the water in a bucket and move valuables out of the way.</li><li>If the ceiling is bulging with water, keep people out of the room.</li><li>Photograph the ceiling and the roof from the ground.</li><li>Call a roofer. A temporary tarp can stop more water getting in until the repair.</li></ol>"),
   ("How the repair usually goes", "<p>The roofer inspects the roof and the attic, traces the water to where it enters, and repairs that spot: new flashing, a new pipe boot, replaced shingles or a section of new underlayment. If the roof is near the end of its life, they may suggest a re-roof instead, and you decide.</p>"),
  ],
  faqs=[("Is a roof leak an emergency?", "An active leak into living space should be handled as soon as possible. Call and say it's leaking now; many roofers can tarp the same day."),
        ("Why does my roof only leak in heavy rain?", "Wind-driven rain reaches spots normal rain doesn't, such as flashing joints and lifted shingle edges. It's still worth fixing before it spreads."),
        ("Can a leak be fixed in winter?", "Yes. Roofers repair leaks year-round and use temporary measures when it's too cold for some materials to seal.")],
  group="Roof Leak"),
 dict(slug="emergency-roof-repair", name="Emergency Roof Repair", icon="siren", short="Roof opened up, water pouring in, storm-hit roofs.",
  title="Emergency Roof Repair | Fast Emergency Roofing Service | RingaRoofer",
  desc="Emergency roof repair when water is coming in or the roof has opened up. Call (855) 635-9281 for fast emergency service from a local roofer.",
  h1="Emergency roof repair, fast",
  lead="Water pouring in, shingles torn off, a tree limb through the roof. Call now for fast emergency service. We'll connect you with a roofing company taking emergency calls in your area.",
  sections=[
   ("When it's an emergency", "<ul class='ticks'><li>Water is coming into the living space and won't stop.</li><li>Part of the roof is open to the sky after wind or a fallen limb.</li><li>The ceiling is bulging or sagging with trapped water.</li><li>More rain or snow is on the way and the roof is already compromised.</li></ul>"),
   ("Safety first", "<ol><li>If the ceiling is sagging, leave the room and keep others out.</li><li>If water is near outlets or light fixtures, switch off power at the breaker only if you can do it from a dry spot.</li><li>Never go up on a roof during or right after a storm.</li><li>If there is fire, a gas smell or an injury, call 911 first.</li></ol>"),
   ("What an emergency roofer does", "<p>The first job is to stop more water getting in, usually with a heavy tarp secured over the opening, or a temporary patch. Once the roof is dry and stable, the roofer comes back to plan the permanent repair or replacement.</p>"),
  ],
  faqs=[("Do roofers come out at night?", "Some do, depending on the area and the weather. Call and tell us what's happening; we'll connect you with a company taking emergency calls."),
        ("How long does a tarp last?", "A properly secured tarp is a short-term fix meant to protect the home until the permanent repair, typically a few weeks."),
        ("Should I take photos?", "Yes. Photograph the roof from the ground and the inside of the home before anything is moved.")],
  group="Emergency Roofing"),
 dict(slug="roof-tarping", name="Emergency Roof Tarping", icon="tarp", short="Temporary tarp to stop water until the repair.",
  title="Emergency Roof Tarp Service Near You | RingaRoofer",
  desc="Emergency roof tarping to stop water getting in after a storm or leak. Call (855) 635-9281 to connect with a local roofer.",
  h1="Emergency roof tarp service",
  lead="A tarp buys time. When the roof is open or leaking badly, a roofer can secure a heavy tarp to keep rain out until the permanent repair.",
  sections=[
   ("When you need a tarp", "<ul class='ticks'><li>Shingles or decking torn away by wind.</li><li>A limb or debris punctured the roof.</li><li>An active leak with more rain in the forecast.</li><li>The roof needs replacing but it can't be done right away.</li></ul>"),
   ("Why not do it yourself", "<p>Climbing a wet, storm-hit roof is one of the most common ways homeowners get hurt. Roofers use fall protection, anchor the tarp properly and route water off the roof, so it holds in wind.</p>"),
   ("After the tarp", "<p>Once the weather clears, the roofer inspects the roof properly and recommends a repair or a re-roof. Keep your photos and notes from the day it happened.</p>"),
  ],
  faqs=[("How fast can a tarp go on?", "Often the same day or the next, depending on demand after a storm. Call early; roofers book up quickly after big weather."),
        ("Will the tarp harm my roof?", "When it's secured correctly, no. A roofer anchors it so it doesn't flap or pull on shingles.")],
  group="Emergency Roofing"),
 dict(slug="storm-roof-repair", name="Storm Roof Repair", icon="storm", short="Wind-lifted shingles, torn flashing, debris impact.",
  title="Storm Roof Repair Near You | Roofers After a Storm | RingaRoofer",
  desc="Roof hit by a storm? Call (855) 635-9281 to connect with a local roofer for storm roof repair: lifted shingles, torn flashing and debris impact.",
  h1="Storm roof repair from a local roofer",
  lead="High wind lifts shingles, tears flashing and throws debris. Call and we'll connect you with a roofer who can inspect the roof and repair it.",
  sections=[
   ("What storms do to roofs", "<ul class='ticks'><li><b>Lifted or creased shingles</b> that no longer seal and later leak.</li><li><b>Missing shingles and ridge caps</b> after strong gusts.</li><li><b>Torn or bent flashing</b> at walls, valleys and vents.</li><li><b>Punctures</b> from limbs and flying debris.</li></ul><p>Some of this can't be seen from the ground. A roofer checks the whole roof, not just the obvious spots.</p>"),
   ("After the storm passes", "<ol><li>Look at the roof from the ground and photograph anything missing or out of place.</li><li>Check the attic and ceilings for new stains.</li><li>Stay off the roof.</li><li>Call a roofer early; demand jumps after big storms.</li></ol>"),
   ("Watch out for storm chasers", "<p>After big storms, out-of-town crews knock on doors. Take your time, ask for a local address and references, get the scope of work in writing, and don't sign anything on the doorstep.</p>"),
  ],
  faqs=[("How soon after a storm should the roof be checked?", "As soon as it's safe. Small openings let water in with the next rain."),
        ("Can storm-hit shingles be repaired, or does the roof need replacing?", "It depends on how widespread the problem is. Scattered missing shingles are usually repaired; widespread creasing may mean a re-roof.")],
  group="Storm & Hail Roofing"),
 dict(slug="hail-roof-repair", name="Hail Roof Repair", icon="hail", short="Bruised and cracked shingles, dented metal.",
  title="Hail Roof Repair & Replacement Near You | RingaRoofer",
  desc="Hail hit your roof? Call (855) 635-9281 to connect with a local roofer for hail roof repair or replacement. Nationwide roofer network.",
  h1="Hail hit your roof? Get it checked by a roofer",
  lead="Hail bruises shingles, knocks off granules and dents metal. The effects often show up months later as leaks. Call and we'll connect you with a roofer who knows hail.",
  sections=[
   ("Signs of hail on a roof", "<ul class='ticks'><li>Dark spots where granules were knocked off.</li><li>Soft, bruised areas on shingles.</li><li>Cracked or split shingles.</li><li>Dents on metal vents, flashing and metal roofing.</li><li>Granules collecting at downspout outlets and on the ground.</li></ul>"),
   ("Hail size matters", "<p>Hail around one inch across and larger can harm asphalt shingles, and bigger stones can crack tile and dent metal. Write down the date of the storm; it helps the roofer and anyone else involved later.</p>"),
   ("Repair or new roof", "<p>If hail marks are scattered, a repair may be enough. If they cover most slopes, a roofer may recommend a full re-roof. Either way, a roofer should walk you through photos of what they found.</p>"),
  ],
  faqs=[("Can I see hail marks from the ground?", "Rarely. Most hail marks are only visible up close, which is why a roofer's inspection matters."),
        ("Is metal roofing hail resistant?", "Metal handles hail well structurally, though large hail can leave cosmetic dents. Ask a roofer about impact-resistant options.")],
  group="Storm & Hail Roofing"),
 dict(slug="roof-replacement", name="Roof Replacement", icon="house", short="Full tear-off and replacement of worn roofs.",
  title="Roof Replacement Near You | Call a Local Roofer | RingaRoofer",
  desc="Roof replacement for worn, aging or storm-hit roofs. Call (855) 635-9281 to connect with a local roofing company for a full replacement.",
  h1="Roof replacement, start with one call",
  lead="Curling shingles, repeated leaks, bald patches or a roof past its age. Call and we'll connect you with a roofing company that handles full replacements in your area.",
  sections=[
   ("Signs it's time for a new roof", "<ul class='ticks'><li>Shingles curling, cupping or cracking across the roof.</li><li>Bald spots and granules piling up at downspouts.</li><li>Leaks in more than one place, or the same leak coming back.</li><li>Daylight through roof boards in the attic.</li><li>A sagging roofline.</li><li>An asphalt roof roughly 20 years old or more.</li></ul>"),
   ("How a replacement works", "<ol><li><b>Inspection:</b> the roofer checks decking, ventilation and flashing.</li><li><b>Material choice:</b> asphalt shingle, metal, tile or flat roofing, depending on your home.</li><li><b>Tear-off:</b> old layers come off down to the decking.</li><li><b>Repairs:</b> soft decking is replaced.</li><li><b>New roof:</b> underlayment, flashing, roofing and ridge vents go on.</li><li><b>Clean-up:</b> debris and nails are cleared from the property.</li></ol><p>Most homes are re-roofed in one to three days, weather permitting.</p>"),
   ("Choosing a roofer", "<p>Ask how long they've worked in your area, who will be on the roof, how they protect your property, and what the written scope of work includes. Get the details in writing before work starts.</p>"),
  ],
  faqs=[("How long does a roof replacement take?", "Most homes take one to three days. Larger or complex roofs, and tile or slate, take longer."),
        ("Can a new roof go over the old one?", "Some areas allow a second layer of shingles, but many roofers prefer a full tear-off so they can check the decking. Ask what they recommend and why."),
        ("What roofing material should I choose?", "It depends on climate, the home's style and how long you plan to stay. See our roof types pages, and ask the roofer to compare options.")],
  group="Roof Replacement"),
 dict(slug="new-roof", name="New Roofs & Re-Roofs", icon="layers", short="New roof installation and re-roofing.",
  title="New Roof Installation & Re-Roofing Near You | RingaRoofer",
  desc="New roof installation and re-roofing: asphalt shingle, metal, tile and flat roofs. Call (855) 635-9281 to connect with a local roofing company.",
  h1="New roofs and re-roofs",
  lead="Whether you're re-roofing an older home or need a new roof on an addition, one call connects you with a roofing company that installs it.",
  sections=[
   ("New roof or re-roof?", "<p>A <b>re-roof</b> replaces the roofing on an existing home, usually with a full tear-off. A <b>new roof</b> goes on new construction, an addition or a home changing to a different material, such as shingle to metal.</p>"),
   ("Materials roofers install", "<ul class='ticks'><li><a href='/roof-types/asphalt-shingle/'>Asphalt shingle</a>, the most common roof in the country.</li><li><a href='/roof-types/metal/'>Metal</a>, including standing seam.</li><li><a href='/roof-types/tile/'>Clay and concrete tile</a>.</li><li><a href='/roof-types/flat/'>Flat roofing</a>: TPO, EPDM and modified bitumen.</li><li><a href='/roof-types/slate/'>Slate</a> and <a href='/roof-types/cedar-shake/'>cedar shake</a>.</li></ul>"),
   ("Plan ahead", "<p>Spring and fall are the busiest seasons for re-roofing in much of the country. Calling a few weeks ahead gives you more choice of dates.</p>"),
  ],
  faqs=[("How long does a new roof last?", "Asphalt shingles commonly last 20 to 30 years, metal 40 years or more, and tile and slate much longer with care. Climate and installation quality matter."),
        ("Do I need to be home during the work?", "Not always, but the roofer will want access to the attic and a clear driveway. Agree the details before the start date.")],
  group="Roof Replacement"),
]

# ---------------------------------------------------------------- roof types
TYPES = [
 dict(slug="asphalt-shingle", name="Asphalt Shingle", icon="shingle",
  title="Asphalt Shingle Roofing: Repair & Replacement | RingaRoofer",
  desc="Asphalt shingle roof repair and replacement, including architectural shingles. Call (855) 635-9281 to connect with a local shingle roofer.",
  h1="Asphalt shingle roofing", lead="The most common roof in America: three-tab and architectural shingles, repaired and replaced by roofers near you.",
  body="<p>Asphalt shingles cover most homes in the country because they suit almost any climate and style. <b>Architectural (dimensional) shingles</b> are thicker, look more textured and handle wind better than older three-tab shingles.</p><h2>Typical lifespan</h2><p>Around 20 to 30 years, shorter in hot, sunny climates and after repeated hail.</p><h2>Common repairs</h2><ul class='ticks'><li>Replacing missing or wind-lifted shingles</li><li>Resealing or replacing flashing and pipe boots</li><li>Ridge cap replacement</li></ul><h2>When to re-roof</h2><p>Widespread curling, cracking, granule loss or repeated leaks usually mean it's time for a new shingle roof.</p>"),
 dict(slug="metal", name="Metal Roofing", icon="metal",
  title="Metal Roofing: Installation, Repair & Standing Seam | RingaRoofer",
  desc="Metal roof installation, replacement and repair, including standing seam. Call (855) 635-9281 to connect with a local metal roofer.",
  h1="Metal roofing", lead="Standing seam and metal shingle roofs, installed and repaired by roofers near you.",
  body="<p>Metal roofs are popular for their long life, fire resistance and ability to shed snow. <b>Standing seam</b> panels have raised seams that hide the fasteners; <b>exposed-fastener</b> panels are simpler; <b>metal shingles</b> mimic the look of shingle, slate or shake.</p><h2>Typical lifespan</h2><p>40 years or more with care.</p><h2>Common repairs</h2><ul class='ticks'><li>Re-securing loose panels and trim</li><li>Replacing worn fastener washers on exposed-fastener roofs</li><li>Sealing seams and flashing</li></ul><h2>Good to know</h2><p>Large hail can leave cosmetic dents. Ask a roofer about impact-resistant panels if you live in hail country.</p>"),
 dict(slug="flat", name="Flat Roofing", icon="flat",
  title="Flat Roof Repair & Replacement: TPO, EPDM, Rubber | RingaRoofer",
  desc="Flat roof repair and replacement: TPO, EPDM rubber and modified bitumen. Call (855) 635-9281 to connect with a local flat roofer.",
  h1="Flat roofing", lead="TPO, EPDM rubber and modified bitumen roofs on homes, porches and additions.",
  body="<p>Flat roofs aren't perfectly flat; they have a slight slope to drain. Because water moves slowly, seams and drains matter most.</p><h2>Main systems</h2><ul class='ticks'><li><b>TPO:</b> white single-ply membrane with heat-welded seams, reflects sun.</li><li><b>EPDM:</b> black rubber membrane, durable and flexible in the cold.</li><li><b>Modified bitumen:</b> layered asphalt-based sheets, common on homes.</li></ul><h2>Common problems</h2><ul class='ticks'><li>Ponding water that doesn't drain</li><li>Split seams and blisters</li><li>Leaks around drains, vents and walls</li></ul>"),
 dict(slug="tile", name="Tile Roofing", icon="tile",
  title="Tile Roof Repair & Replacement: Clay & Concrete | RingaRoofer",
  desc="Clay and concrete tile roof repair and replacement. Call (855) 635-9281 to connect with a local tile roofer.",
  h1="Tile roofing", lead="Clay and concrete tile roofs, common across the South and West, repaired and replaced by roofers who know tile.",
  body="<p>Tile roofs can last for decades, but the tiles themselves aren't the whole roof: the <b>underlayment</b> beneath them does much of the waterproofing and wears out sooner.</p><h2>Common repairs</h2><ul class='ticks'><li>Replacing cracked or slipped tiles</li><li>Re-laying tiles over new underlayment</li><li>Repairing flashing and ridge details</li></ul><h2>Good to know</h2><p>Walking on tile can crack it. Leave inspections to a roofer who works with tile.</p>"),
 dict(slug="slate", name="Slate Roofing", icon="slate",
  title="Slate Roof Repair & Replacement | RingaRoofer",
  desc="Slate roof repair and replacement from roofers who work with natural slate. Call (855) 635-9281 to connect with a local roofer.",
  h1="Slate roofing", lead="Natural slate roofs, common on older homes in the Northeast and Mid-Atlantic, repaired by roofers who specialize in slate.",
  body="<p>Slate is one of the longest-lasting roofing materials, often outliving the nails and flashing that hold it. Many slate problems are repairable one slate at a time.</p><h2>Common repairs</h2><ul class='ticks'><li>Replacing cracked or missing slates</li><li>Copper or metal flashing repairs</li><li>Re-securing slipped slates</li></ul><h2>Good to know</h2><p>Slate needs a specialist. Ask the roofer about their experience with slate specifically.</p>"),
 dict(slug="cedar-shake", name="Cedar Shake", icon="shake",
  title="Cedar Shake Roof Repair & Replacement | RingaRoofer",
  desc="Cedar shake and wood shingle roof repair and replacement. Call (855) 635-9281 to connect with a local roofer.",
  h1="Cedar shake roofing", lead="Wood shake and shingle roofs, repaired and replaced by roofers near you.",
  body="<p>Cedar shake gives a natural, textured look. It needs airflow and upkeep to last, especially in damp climates.</p><h2>Common repairs</h2><ul class='ticks'><li>Replacing split or curled shakes</li><li>Clearing moss and debris that hold moisture</li><li>Flashing repairs</li></ul><h2>Good to know</h2><p>Some areas have fire rules for wood roofs. A local roofer will know what's allowed where you live.</p>"),
]

# ---------------------------------------------------------------- library articles
ARTICLES = [
 dict(slug="roof-leaking-what-to-do-now", title="Roof Leaking? What to Do Right Now | RingaRoofer",
  h1="Roof leaking? What to do right now",
  desc="A simple plan for the first hour of a roof leak: protect your home, stay safe, document everything and get a roofer on the way.",
  lead="The first hour of a roof leak, step by step.",
  body="<h2>1. Catch the water</h2><p>Put a bucket under the drip and a towel or board under the bucket to stop splashing. Move furniture, electronics and rugs out of the way.</p><h2>2. Check the ceiling</h2><p>If the ceiling is bulging, water is pooling above it. Keep people out of the room. A roofer or handyman may relieve the pressure safely; don't stand under it.</p><h2>3. Mind the electricity</h2><p>If water is near light fixtures or outlets, switch off that circuit at the breaker, but only from a dry spot.</p><h2>4. Photograph everything</h2><p>Photos of the ceiling, the wet area and the roof from the ground, with the date, help the roofer and anyone else involved later.</p><h2>5. Stay off the roof</h2><p>Wet roofs are slippery. Leave tarping to a roofer with the right equipment.</p><h2>6. Call a roofer</h2><p>Tell them it's leaking now. Many can tarp the same day and come back for the permanent repair.</p>"),
 dict(slug="signs-you-need-a-new-roof", title="8 Signs You Need a New Roof | RingaRoofer",
  h1="8 signs you need a new roof",
  desc="Curling shingles, bald spots, repeat leaks and more: eight signs it's time to replace your roof, and what to do next.",
  lead="When repairs stop being enough.",
  body="<ol class='big'><li><b>Curling or cupping shingles</b> across whole slopes.</li><li><b>Bald spots</b> where granules have worn away.</li><li><b>Granules at the downspouts</b> after every rain.</li><li><b>Cracked or missing shingles</b> in several places.</li><li><b>Leaks that keep coming back</b>, or new leaks in different rooms.</li><li><b>Daylight in the attic</b> through the roof boards.</li><li><b>A sagging roofline</b> or soft spots when a roofer walks it.</li><li><b>Age:</b> most asphalt roofs are near the end at 20 to 30 years.</li></ol><p>Seeing two or three of these? Call a roofer to look at the whole roof and talk you through repair versus replacement.</p>"),
 dict(slug="choosing-a-roofing-material", title="Shingle, Metal, Tile or Flat? Choosing a Roofing Material | RingaRoofer",
  h1="Shingle, metal, tile or flat? Choosing a roofing material",
  desc="Compare asphalt shingle, metal, tile, slate, cedar shake and flat roofing by lifespan, climate fit and upkeep.",
  lead="A plain comparison to take into your conversation with a roofer.",
  body="<div class='tbl'><table><thead><tr><th>Material</th><th>Typical life</th><th>Good fit</th><th>Upkeep</th></tr></thead><tbody><tr><td>Asphalt shingle</td><td>20–30 yrs</td><td>Almost anywhere</td><td>Light</td></tr><tr><td>Metal</td><td>40+ yrs</td><td>Snow, wind, wildfire areas</td><td>Light</td></tr><tr><td>Clay / concrete tile</td><td>50+ yrs (underlayment less)</td><td>Hot, sunny climates</td><td>Medium</td></tr><tr><td>Slate</td><td>75+ yrs</td><td>Older homes, cold climates</td><td>Specialist</td></tr><tr><td>Cedar shake</td><td>20–40 yrs</td><td>Drier, airy settings</td><td>Higher</td></tr><tr><td>Flat (TPO, EPDM, mod-bit)</td><td>15–30 yrs</td><td>Near-flat sections, additions</td><td>Medium</td></tr></tbody></table></div><p>Your roof's pitch, local building rules and how long you'll stay in the home all matter. A roofer who sees the house can narrow it down quickly.</p>"),
 dict(slug="after-a-hailstorm", title="After a Hailstorm: Roof Checklist for Homeowners | RingaRoofer",
  h1="After a hailstorm: a roof checklist",
  desc="What to check after hail: marks on vents and metal, granules at downspouts, ceiling stains, and when to call a roofer.",
  lead="Ten minutes on the ground can tell you whether to call a roofer.",
  body="<ul class='ticks'><li>Write down the storm date and the hail size if you saw it.</li><li>Look for dents on metal vents, flashing, mailboxes and outdoor units.</li><li>Check for granules washing out of downspouts.</li><li>Look for shingle pieces in the yard.</li><li>Check ceilings and the attic for new stains over the next few rains.</li><li>Photograph everything from the ground.</li></ul><p>Hail marks on shingles are rarely visible from the ground. If you found signs above, call a roofer for a proper look. And be cautious with door-to-door crews after big storms.</p>"),
]

# ---------------------------------------------------------------- states
REGIONS = {
 "Northeast": "Snow load, ice dams and freeze-thaw cycles are the main roof stresses. Nor'easters bring wind-driven rain, and many older homes have slate or multi-layer shingle roofs.",
 "Southeast": "Hurricanes and tropical storms, heavy summer thunderstorms, high humidity and strong sun. Wind-resistant shingles, metal and tile are common, and quick tarping after storms matters.",
 "Midwest": "Hail and severe thunderstorms in spring and summer, heavy snow and ice dams in winter. Asphalt shingles dominate, with metal growing in rural areas.",
 "South Central": "The heart of hail country, with tornadoes, straight-line winds and intense summer heat. Roofs here see some of the most storm activity in the nation.",
 "Mountain West": "Big temperature swings, intense sun at altitude, hail on the Front Range and heavy snow in the mountains. Metal and impact-resistant shingles are popular.",
 "West": "Strong sun and heat in the desert, wildfire zones, winter storms in the Pacific Northwest. Tile and flat roofs are common in the Southwest, shingle and metal farther north.",
}
# code, name, region, cities, extra line
STATES = [
 ("AL","Alabama","Southeast",["Birmingham","Huntsville","Montgomery","Mobile","Tuscaloosa"],"Gulf storms reach the south, and spring tornado outbreaks hit the north and central parts of the state."),
 ("AK","Alaska","West",["Anchorage","Fairbanks","Juneau","Wasilla","Sitka"],"Heavy snow loads, long winters and ice build-up are the main roof concerns."),
 ("AZ","Arizona","West",["Phoenix","Tucson","Mesa","Chandler","Scottsdale"],"Extreme sun and heat age roofs quickly, and monsoon storms bring sudden wind and rain in summer."),
 ("AR","Arkansas","South Central",["Little Rock","Fayetteville","Fort Smith","Springdale","Jonesboro"],"Spring hail, tornadoes and heavy thunderstorms drive most roof calls."),
 ("CA","California","West",["Los Angeles","San Diego","San Jose","Sacramento","Fresno"],"Tile and flat roofs are common in the south; winter atmospheric-river storms test roofs in the north."),
 ("CO","Colorado","Mountain West",["Denver","Colorado Springs","Aurora","Fort Collins","Lakewood"],"The Front Range is one of the most hail-prone areas in the country."),
 ("CT","Connecticut","Northeast",["Bridgeport","New Haven","Stamford","Hartford","Waterbury"],"Nor'easters, snow and ice dams, with occasional tropical storms late in summer."),
 ("DE","Delaware","Northeast",["Wilmington","Dover","Newark","Middletown","Smyrna"],"Coastal storms and nor'easters bring wind-driven rain."),
 ("FL","Florida","Southeast",["Jacksonville","Miami","Tampa","Orlando","St. Petersburg"],"Hurricane season runs June through November, and roofs here follow some of the strictest wind rules in the nation."),
 ("GA","Georgia","Southeast",["Atlanta","Augusta","Columbus","Savannah","Athens"],"Severe thunderstorms, occasional hail around Atlanta and tropical storms near the coast."),
 ("HI","Hawaii","West",["Honolulu","Hilo","Kailua","Kapolei","Kahului"],"Trade winds, heavy rain, salt air and strong sun wear roofs in their own way."),
 ("ID","Idaho","Mountain West",["Boise","Meridian","Nampa","Idaho Falls","Pocatello"],"Snow loads in the mountains and hot, dry summers in the valleys."),
 ("IL","Illinois","Midwest",["Chicago","Aurora","Naperville","Joliet","Rockford"],"Spring hail and wind, then snow and ice dams in winter."),
 ("IN","Indiana","Midwest",["Indianapolis","Fort Wayne","Evansville","South Bend","Carmel"],"Severe thunderstorms, hail and damaging wind are common from spring into summer."),
 ("IA","Iowa","Midwest",["Des Moines","Cedar Rapids","Davenport","Sioux City","Iowa City"],"Hail and derecho winds in summer, snow and ice in winter."),
 ("KS","Kansas","South Central",["Wichita","Overland Park","Kansas City","Olathe","Topeka"],"Among the most hail- and tornado-prone states in the country."),
 ("KY","Kentucky","Southeast",["Louisville","Lexington","Bowling Green","Owensboro","Covington"],"Spring storms, hail and occasional ice storms in winter."),
 ("LA","Louisiana","Southeast",["New Orleans","Baton Rouge","Shreveport","Lafayette","Lake Charles"],"Hurricanes, tropical rain and humidity make fast tarping and wind-resistant roofs essential."),
 ("ME","Maine","Northeast",["Portland","Lewiston","Bangor","South Portland","Auburn"],"Heavy snow, ice dams and coastal nor'easters."),
 ("MD","Maryland","Northeast",["Baltimore","Columbia","Germantown","Silver Spring","Frederick"],"Summer thunderstorms, nor'easters and the odd tropical system."),
 ("MA","Massachusetts","Northeast",["Boston","Worcester","Springfield","Cambridge","Lowell"],"Snow loads, ice dams and nor'easters; many older homes have slate."),
 ("MI","Michigan","Midwest",["Detroit","Grand Rapids","Warren","Sterling Heights","Ann Arbor"],"Lake-effect snow, ice dams and summer wind storms."),
 ("MN","Minnesota","Midwest",["Minneapolis","St. Paul","Rochester","Duluth","Bloomington"],"Hail in summer and some of the harshest winters in the continental U.S.."),
 ("MS","Mississippi","Southeast",["Jackson","Gulfport","Southaven","Hattiesburg","Biloxi"],"Tornadoes inland and hurricanes on the coast."),
 ("MO","Missouri","Midwest",["Kansas City","St. Louis","Springfield","Columbia","Independence"],"Hail and tornadoes in spring, ice storms in winter."),
 ("MT","Montana","Mountain West",["Billings","Missoula","Great Falls","Bozeman","Butte"],"Hail on the plains, heavy snow in the mountains and strong chinook winds."),
 ("NE","Nebraska","South Central",["Omaha","Lincoln","Bellevue","Grand Island","Kearney"],"Frequent large hail and severe storms across the state."),
 ("NV","Nevada","West",["Las Vegas","Henderson","Reno","North Las Vegas","Sparks"],"Intense desert sun and heat in the south, snow and wind around Reno."),
 ("NH","New Hampshire","Northeast",["Manchester","Nashua","Concord","Dover","Rochester"],"Snow, ice dams and nor'easters."),
 ("NJ","New Jersey","Northeast",["Newark","Jersey City","Paterson","Elizabeth","Toms River"],"Nor'easters, coastal storms and summer thunderstorms."),
 ("NM","New Mexico","West",["Albuquerque","Las Cruces","Rio Rancho","Santa Fe","Roswell"],"Strong sun, monsoon storms and hail in the east of the state; flat roofs are common."),
 ("NY","New York","Northeast",["New York City","Buffalo","Rochester","Yonkers","Syracuse"],"Lake-effect snow upstate, nor'easters and coastal storms downstate."),
 ("NC","North Carolina","Southeast",["Charlotte","Raleigh","Greensboro","Durham","Wilmington"],"Hurricanes on the coast, severe storms and occasional ice inland."),
 ("ND","North Dakota","Midwest",["Fargo","Bismarck","Grand Forks","Minot","West Fargo"],"Summer hail and long, cold winters."),
 ("OH","Ohio","Midwest",["Columbus","Cleveland","Cincinnati","Toledo","Akron"],"Spring storms and wind, lake-effect snow in the northeast."),
 ("OK","Oklahoma","South Central",["Oklahoma City","Tulsa","Norman","Broken Arrow","Edmond"],"Tornado Alley: hail and high wind are a regular part of spring."),
 ("OR","Oregon","West",["Portland","Salem","Eugene","Gresham","Hillsboro"],"Long wet winters, moss and wind storms on the coast."),
 ("PA","Pennsylvania","Northeast",["Philadelphia","Pittsburgh","Allentown","Reading","Erie"],"Snow and ice, summer thunderstorms and many older slate roofs."),
 ("RI","Rhode Island","Northeast",["Providence","Warwick","Cranston","Pawtucket","Newport"],"Nor'easters and coastal storms."),
 ("SC","South Carolina","Southeast",["Charleston","Columbia","North Charleston","Greenville","Myrtle Beach"],"Hurricanes on the coast and strong summer storms inland."),
 ("SD","South Dakota","Midwest",["Sioux Falls","Rapid City","Aberdeen","Brookings","Watertown"],"Frequent large hail in summer and blizzards in winter."),
 ("TN","Tennessee","Southeast",["Nashville","Memphis","Knoxville","Chattanooga","Clarksville"],"Spring tornadoes, hail and severe thunderstorms."),
 ("TX","Texas","South Central",["Houston","San Antonio","Dallas","Austin","Fort Worth"],"Leads the nation in hail events, with hurricanes and tropical storms along the Gulf Coast."),
 ("UT","Utah","Mountain West",["Salt Lake City","West Valley City","Provo","West Jordan","Orem"],"Snow loads, wind and strong summer sun."),
 ("VT","Vermont","Northeast",["Burlington","South Burlington","Rutland","Essex Junction","Barre"],"Heavy snow and ice dams; metal roofs are common."),
 ("VA","Virginia","Southeast",["Virginia Beach","Chesapeake","Norfolk","Richmond","Arlington"],"Coastal storms in the east, snow and ice in the west."),
 ("WA","Washington","West",["Seattle","Spokane","Tacoma","Vancouver","Bellevue"],"Wet winters and moss west of the Cascades, snow and heat to the east."),
 ("WV","West Virginia","Southeast",["Charleston","Huntington","Morgantown","Parkersburg","Wheeling"],"Snow, ice and summer thunderstorms."),
 ("WI","Wisconsin","Midwest",["Milwaukee","Madison","Green Bay","Kenosha","Racine"],"Hail and wind in summer, snow and ice dams in winter."),
 ("WY","Wyoming","Mountain West",["Cheyenne","Casper","Laramie","Gillette","Rock Springs"],"Hail on the plains, strong wind and heavy mountain snow."),
 ("DC","Washington, D.C.","Northeast",["Capitol Hill","Georgetown","Navy Yard","Petworth","Anacostia"],"Summer thunderstorms, nor'easters and many flat rowhouse roofs."),
]
